### ISSUE TITLE
AttributeError: 'GroupParams' object has no attribute 'znear_quantile'

### ISSUE THREAD

**Issue by thlee00** [graphdeco-inria/gaussian-splatting-relighting#3]
Hello,

I am encountering the following error when I attempt to render a video using your pretrained model by running ```render_relighting_video.sh```.
```
Traceback (most recent call last):
  File "/workspace/gaussian-splatting-relighting/_render_relighting_video.py", line 231, in <module>
    render_sets(args, modelParams, args.iteration, pipeline.extract(args), args.skip_train, args.skip_test)
  File "/workspace/gaussian-splatting-relighting/_render_relighting_video.py", line 182, in render_sets
    scene = Scene(modelParams, pipeline, gaussians, load_iteration=iteration, shuffle=False, adjust_znear=True)
  File "/workspace/gaussian-splatting-relighting/scene/scene.py", line 114, in __init__
    self.autoadjust_znear()
  File "/workspace/gaussian-splatting-relighting/scene/scene.py", line 134, in autoadjust_znear
    camera.znear = (-points_in_frustrum[:, 2]).quantile(self.modelParams.znear_quantile) * self.modelParams.znear_scale
AttributeError: 'GroupParams' object has no attribute 'znear_quantile'
```
I noticed that there are ```znear_quantile``` and ```znear_scale``` in the ```GroupParams``` class.
However, in ```cfg_args```, I only see ```znear_autoadjust``` and ```znear_fraction```, but not ```znear_quantile``` and ```znear_scale```.
```
self.znear_pruning = True # if enabled and znear_fraction !=, prune the gaussians that move in front of any camera's near clipping plane
self.znear_quantile = 0.01
self.znear_scale = 0.9
```
```
znear_autoadjust=True, znear_fraction=1.0, znear_pruning=True
```

Could you please advise me on how to fix this error?

Thank you!

**Comment by yohan-pg** [comment]
Hello,

Sorry for the slow reply.  That's quite strange. Are you using a pretrained scene or training from scratch?

**Comment by yohan-pg** [comment]
I believe what's happening is that the config is being loaded from pretrained scenes in the rendering script, and at least some of them do not have `znear_quantile` in their config (I don't think their config was actually different, just that the parameter was hard-coded or named different back when the scenes were trained). 

So what I recommend is to set these settings to their default values if they are absent in the config; I added a few lines to the rendering script which does this.
